language: node_js
node_js:
  - node
env:
  - PUBLIC_URL=/kcquest
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
  - npm run typecheck
script:
  - npm run update
  - npm run build
before_deploy:
  - cp README.md dist/
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: false
    local-dir: dist
    on:
      branch: master
      condition: $GITHUB_TOKEN
